/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlockListConfiguration } from './BlockListConfiguration';
import {
    BlockListConfigurationFromJSON,
    BlockListConfigurationToJSON
} from './BlockListConfiguration';
import type { BlockMeta } from './BlockMeta';
import {
    BlockMetaFromJSON,
    BlockMetaToJSON
} from './BlockMeta';
import type { BlockMetadataType } from './BlockMetadataType';
import {
    BlockMetadataTypeFromJSON,
    BlockMetadataTypeToJSON
} from './BlockMetadataType';
import type { BlockReferenceFetchPolicy } from './BlockReferenceFetchPolicy';
import {
    BlockReferenceFetchPolicyFromJSON,
    BlockReferenceFetchPolicyToJSON
} from './BlockReferenceFetchPolicy';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityToJSON
} from './Entity';
import type { ListConfig } from './ListConfig';
import {
    ListConfigFromJSON,
    ListConfigToJSON
} from './ListConfig';
import type { ListDisplayConfig } from './ListDisplayConfig';
import {
    ListDisplayConfigFromJSON,
    ListDisplayConfigToJSON
} from './ListDisplayConfig';
import type { Presentation } from './Presentation';
import {
    PresentationFromJSON,
    PresentationToJSON
} from './Presentation';
import type { Projection } from './Projection';
import {
    ProjectionFromJSON,
    ProjectionToJSON
} from './Projection';
import type { ReferenceItem } from './ReferenceItem';
import {
    ReferenceItemFromJSON,
    ReferenceItemToJSON
} from './ReferenceItem';

/**
 * 
 * @export
 * @interface BlockReferenceMetadata
 */
export interface BlockReferenceMetadata {
    /**
     * 
     * @type {boolean}
     * @memberof BlockReferenceMetadata
     */
    deletable: boolean;
    /**
     * 
     * @type {BlockMeta}
     * @memberof BlockReferenceMetadata
     */
    meta: BlockMeta;
    /**
     * 
     * @type {boolean}
     * @memberof BlockReferenceMetadata
     */
    readonly: boolean;
    /**
     * 
     * @type {BlockMetadataType}
     * @memberof BlockReferenceMetadata
     */
    type: BlockMetadataType;
    /**
     * 
     * @type {Presentation}
     * @memberof BlockReferenceMetadata
     */
    presentation: Presentation;
    /**
     * 
     * @type {Array<ReferenceItem>}
     * @memberof BlockReferenceMetadata
     */
    items: Array<ReferenceItem>;
    /**
     * 
     * @type {Projection}
     * @memberof BlockReferenceMetadata
     */
    projection: Projection;
    /**
     * 
     * @type {Entity}
     * @memberof BlockReferenceMetadata
     */
    listType?: Entity | null;
    /**
     * 
     * @type {ListDisplayConfig}
     * @memberof BlockReferenceMetadata
     */
    display: ListDisplayConfig;
    /**
     * 
     * @type {ListConfig}
     * @memberof BlockReferenceMetadata
     */
    config: ListConfig;
    /**
     * 
     * @type {boolean}
     * @memberof BlockReferenceMetadata
     */
    allowDuplicates: boolean;
    /**
     * 
     * @type {number}
     * @memberof BlockReferenceMetadata
     */
    expandDepth: number;
    /**
     * 
     * @type {ReferenceItem}
     * @memberof BlockReferenceMetadata
     */
    item: ReferenceItem;
    /**
     * 
     * @type {object}
     * @memberof BlockReferenceMetadata
     */
    data: object;
    /**
     * 
     * @type {BlockListConfiguration}
     * @memberof BlockReferenceMetadata
     */
    listConfig?: BlockListConfiguration | null;
    /**
     * 
     * @type {BlockReferenceFetchPolicy}
     * @memberof BlockReferenceMetadata
     */
    fetchPolicy: BlockReferenceFetchPolicy;
    /**
     * 
     * @type {string}
     * @memberof BlockReferenceMetadata
     */
    path: string;
}



/**
 * Check if a given object implements the BlockReferenceMetadata interface.
 */
export function instanceOfBlockReferenceMetadata(value: object): value is BlockReferenceMetadata {
    if (!('deletable' in value) || value['deletable'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('readonly' in value) || value['readonly'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('presentation' in value) || value['presentation'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('projection' in value) || value['projection'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('allowDuplicates' in value) || value['allowDuplicates'] === undefined) return false;
    if (!('expandDepth' in value) || value['expandDepth'] === undefined) return false;
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('fetchPolicy' in value) || value['fetchPolicy'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function BlockReferenceMetadataFromJSON(json: any): BlockReferenceMetadata {
    return BlockReferenceMetadataFromJSONTyped(json, false);
}

export function BlockReferenceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockReferenceMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'deletable': json['deletable'],
        'meta': BlockMetaFromJSON(json['meta']),
        'readonly': json['readonly'],
        'type': BlockMetadataTypeFromJSON(json['type']),
        'presentation': PresentationFromJSON(json['presentation']),
        'items': ((json['items'] as Array<any>).map(ReferenceItemFromJSON)),
        'projection': ProjectionFromJSON(json['projection']),
        'listType': json['listType'] == null ? undefined : EntityFromJSON(json['listType']),
        'display': ListDisplayConfigFromJSON(json['display']),
        'config': ListConfigFromJSON(json['config']),
        'allowDuplicates': json['allowDuplicates'],
        'expandDepth': json['expandDepth'],
        'item': ReferenceItemFromJSON(json['item']),
        'data': json['data'],
        'listConfig': json['listConfig'] == null ? undefined : BlockListConfigurationFromJSON(json['listConfig']),
        'fetchPolicy': BlockReferenceFetchPolicyFromJSON(json['fetchPolicy']),
        'path': json['path'],
    };
}

export function BlockReferenceMetadataToJSON(json: any): BlockReferenceMetadata {
    return BlockReferenceMetadataToJSONTyped(json, false);
}

export function BlockReferenceMetadataToJSONTyped(value?: BlockReferenceMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deletable': value['deletable'],
        'meta': BlockMetaToJSON(value['meta']),
        'readonly': value['readonly'],
        'type': BlockMetadataTypeToJSON(value['type']),
        'presentation': PresentationToJSON(value['presentation']),
        'items': ((value['items'] as Array<any>).map(ReferenceItemToJSON)),
        'projection': ProjectionToJSON(value['projection']),
        'listType': EntityToJSON(value['listType']),
        'display': ListDisplayConfigToJSON(value['display']),
        'config': ListConfigToJSON(value['config']),
        'allowDuplicates': value['allowDuplicates'],
        'expandDepth': value['expandDepth'],
        'item': ReferenceItemToJSON(value['item']),
        'data': value['data'],
        'listConfig': BlockListConfigurationToJSON(value['listConfig']),
        'fetchPolicy': BlockReferenceFetchPolicyToJSON(value['fetchPolicy']),
        'path': value['path'],
    };
}

