/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlockRenderStructure } from './BlockRenderStructure';
import {
    BlockRenderStructureFromJSON,
    BlockRenderStructureToJSON
} from './BlockRenderStructure';
import type { FormStructure } from './FormStructure';
import {
    FormStructureFromJSON,
    FormStructureToJSON
} from './FormStructure';

/**
 * 
 * @export
 * @interface BlockDisplay
 */
export interface BlockDisplay {
    /**
     * 
     * @type {FormStructure}
     * @memberof BlockDisplay
     */
    form: FormStructure;
    /**
     * 
     * @type {BlockRenderStructure}
     * @memberof BlockDisplay
     */
    render: BlockRenderStructure;
}

/**
 * Check if a given object implements the BlockDisplay interface.
 */
export function instanceOfBlockDisplay(value: object): value is BlockDisplay {
    if (!('form' in value) || value['form'] === undefined) return false;
    if (!('render' in value) || value['render'] === undefined) return false;
    return true;
}

export function BlockDisplayFromJSON(json: any): BlockDisplay {
    return BlockDisplayFromJSONTyped(json, false);
}

export function BlockDisplayFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDisplay {
    if (json == null) {
        return json;
    }
    return {
        
        'form': FormStructureFromJSON(json['form']),
        'render': BlockRenderStructureFromJSON(json['render']),
    };
}

export function BlockDisplayToJSON(json: any): BlockDisplay {
    return BlockDisplayToJSONTyped(json, false);
}

export function BlockDisplayToJSONTyped(value?: BlockDisplay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'form': FormStructureToJSON(value['form']),
        'render': BlockRenderStructureToJSON(value['render']),
    };
}

