/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListConfig } from './ListConfig';
import {
    ListConfigFromJSON,
    ListConfigToJSON
} from './ListConfig';
import type { ListDisplayConfig } from './ListDisplayConfig';
import {
    ListDisplayConfigFromJSON,
    ListDisplayConfigToJSON
} from './ListDisplayConfig';

/**
 * 
 * @export
 * @interface BlockListConfiguration
 */
export interface BlockListConfiguration {
    /**
     * 
     * @type {Array<string>}
     * @memberof BlockListConfiguration
     */
    listType?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof BlockListConfiguration
     */
    allowDuplicates: boolean;
    /**
     * 
     * @type {ListDisplayConfig}
     * @memberof BlockListConfiguration
     */
    display: ListDisplayConfig;
    /**
     * 
     * @type {ListConfig}
     * @memberof BlockListConfiguration
     */
    config: ListConfig;
}

/**
 * Check if a given object implements the BlockListConfiguration interface.
 */
export function instanceOfBlockListConfiguration(value: object): value is BlockListConfiguration {
    if (!('allowDuplicates' in value) || value['allowDuplicates'] === undefined) return false;
    if (!('display' in value) || value['display'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function BlockListConfigurationFromJSON(json: any): BlockListConfiguration {
    return BlockListConfigurationFromJSONTyped(json, false);
}

export function BlockListConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockListConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'listType': json['listType'] == null ? undefined : json['listType'],
        'allowDuplicates': json['allowDuplicates'],
        'display': ListDisplayConfigFromJSON(json['display']),
        'config': ListConfigFromJSON(json['config']),
    };
}

export function BlockListConfigurationToJSON(json: any): BlockListConfiguration {
    return BlockListConfigurationToJSONTyped(json, false);
}

export function BlockListConfigurationToJSONTyped(value?: BlockListConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listType': value['listType'],
        'allowDuplicates': value['allowDuplicates'],
        'display': ListDisplayConfigToJSON(value['display']),
        'config': ListConfigToJSON(value['config']),
    };
}

