/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeToJSON
} from './Node';

/**
 * 
 * @export
 * @interface BlockTree
 */
export interface BlockTree {
    /**
     * 
     * @type {Node}
     * @memberof BlockTree
     */
    root: Node;
}

/**
 * Check if a given object implements the BlockTree interface.
 */
export function instanceOfBlockTree(value: object): value is BlockTree {
    if (!('root' in value) || value['root'] === undefined) return false;
    return true;
}

export function BlockTreeFromJSON(json: any): BlockTree {
    return BlockTreeFromJSONTyped(json, false);
}

export function BlockTreeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockTree {
    if (json == null) {
        return json;
    }
    return {
        
        'root': NodeFromJSON(json['root']),
    };
}

export function BlockTreeToJSON(json: any): BlockTree {
    return BlockTreeToJSONTyped(json, false);
}

export function BlockTreeToJSONTyped(value?: BlockTree | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'root': NodeToJSON(value['root']),
    };
}

