/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AddBlockOperation } from './AddBlockOperation';
import {
    AddBlockOperationFromJSONTyped,
    AddBlockOperationToJSON,
    instanceOfAddBlockOperation
} from './AddBlockOperation';
import type { MoveBlockOperation } from './MoveBlockOperation';
import {
    instanceOfMoveBlockOperation,
    MoveBlockOperationFromJSONTyped,
    MoveBlockOperationToJSON
} from './MoveBlockOperation';
import type { RemoveBlockOperation } from './RemoveBlockOperation';
import {
    instanceOfRemoveBlockOperation,
    RemoveBlockOperationFromJSONTyped,
    RemoveBlockOperationToJSON
} from './RemoveBlockOperation';
import type { ReorderBlockOperation } from './ReorderBlockOperation';
import {
    instanceOfReorderBlockOperation,
    ReorderBlockOperationFromJSONTyped,
    ReorderBlockOperationToJSON
} from './ReorderBlockOperation';
import type { UpdateBlockOperation } from './UpdateBlockOperation';
import {
    instanceOfUpdateBlockOperation,
    UpdateBlockOperationFromJSONTyped,
    UpdateBlockOperationToJSON
} from './UpdateBlockOperation';

/**
 * @type BlockOperation
 * 
 * @export
 */
export type BlockOperation = AddBlockOperation | MoveBlockOperation | RemoveBlockOperation | ReorderBlockOperation | UpdateBlockOperation;

export function BlockOperationFromJSON(json: any): BlockOperation {
    return BlockOperationFromJSONTyped(json, false);
}

export function BlockOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockOperation {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAddBlockOperation(json)) {
        return AddBlockOperationFromJSONTyped(json, true);
    }
    if (instanceOfMoveBlockOperation(json)) {
        return MoveBlockOperationFromJSONTyped(json, true);
    }
    if (instanceOfRemoveBlockOperation(json)) {
        return RemoveBlockOperationFromJSONTyped(json, true);
    }
    if (instanceOfReorderBlockOperation(json)) {
        return ReorderBlockOperationFromJSONTyped(json, true);
    }
    if (instanceOfUpdateBlockOperation(json)) {
        return UpdateBlockOperationFromJSONTyped(json, true);
    }
    return {} as any;
}

export function BlockOperationToJSON(json: any): any {
    return BlockOperationToJSONTyped(json, false);
}

export function BlockOperationToJSONTyped(value?: BlockOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAddBlockOperation(value)) {
        return AddBlockOperationToJSON(value as AddBlockOperation);
    }
    if (instanceOfMoveBlockOperation(value)) {
        return MoveBlockOperationToJSON(value as MoveBlockOperation);
    }
    if (instanceOfRemoveBlockOperation(value)) {
        return RemoveBlockOperationToJSON(value as RemoveBlockOperation);
    }
    if (instanceOfReorderBlockOperation(value)) {
        return ReorderBlockOperationToJSON(value as ReorderBlockOperation);
    }
    if (instanceOfUpdateBlockOperation(value)) {
        return UpdateBlockOperationToJSON(value as UpdateBlockOperation);
    }
    return {};
}

