/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ReferenceItemBlockTree } from './ReferenceItemBlockTree';
import {
    ReferenceItemBlockTreeFromJSON,
    ReferenceItemBlockTreeToJSON
} from './ReferenceItemBlockTree';
import type { ReferenceType } from './ReferenceType';
import {
    ReferenceTypeFromJSON,
    ReferenceTypeToJSON
} from './ReferenceType';

/**
 * Reference to another block tree
 * @export
 * @interface BlockTreeReference
 */
export interface BlockTreeReference {
    /**
     * 
     * @type {ReferenceType}
     * @memberof BlockTreeReference
     */
    type: ReferenceType;
    /**
     * 
     * @type {ReferenceItemBlockTree}
     * @memberof BlockTreeReference
     */
    reference?: ReferenceItemBlockTree | null;
}



/**
 * Check if a given object implements the BlockTreeReference interface.
 */
export function instanceOfBlockTreeReference(value: object): value is BlockTreeReference {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function BlockTreeReferenceFromJSON(json: any): BlockTreeReference {
    return BlockTreeReferenceFromJSONTyped(json, false);
}

export function BlockTreeReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockTreeReference {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ReferenceTypeFromJSON(json['type']),
        'reference': json['reference'] == null ? undefined : ReferenceItemBlockTreeFromJSON(json['reference']),
    };
}

export function BlockTreeReferenceToJSON(json: any): BlockTreeReference {
    return BlockTreeReferenceToJSONTyped(json, false);
}

export function BlockTreeReferenceToJSONTyped(value?: BlockTreeReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ReferenceTypeToJSON(value['type']),
        'reference': ReferenceItemBlockTreeToJSON(value['reference']),
    };
}

