/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BusinessDefinitionResult } from './BusinessDefinitionResult';
import {
    BusinessDefinitionResultFromJSON,
    BusinessDefinitionResultToJSON
} from './BusinessDefinitionResult';
import type { InviteResult } from './InviteResult';
import {
    InviteResultFromJSON,
    InviteResultToJSON
} from './InviteResult';
import type { TemplateInstallResult } from './TemplateInstallResult';
import {
    TemplateInstallResultFromJSON,
    TemplateInstallResultToJSON
} from './TemplateInstallResult';
import type { UserDisplay } from './UserDisplay';
import {
    UserDisplayFromJSON,
    UserDisplayToJSON
} from './UserDisplay';
import type { Workspace } from './Workspace';
import {
    WorkspaceFromJSON,
    WorkspaceToJSON
} from './Workspace';

/**
 * 
 * @export
 * @interface CompleteOnboardingResponse
 */
export interface CompleteOnboardingResponse {
    /**
     * 
     * @type {Workspace}
     * @memberof CompleteOnboardingResponse
     */
    workspace: Workspace;
    /**
     * 
     * @type {UserDisplay}
     * @memberof CompleteOnboardingResponse
     */
    user: UserDisplay;
    /**
     * 
     * @type {TemplateInstallResult}
     * @memberof CompleteOnboardingResponse
     */
    templateResult: TemplateInstallResult;
    /**
     * 
     * @type {Array<InviteResult>}
     * @memberof CompleteOnboardingResponse
     */
    inviteResults: Array<InviteResult>;
    /**
     * 
     * @type {Array<BusinessDefinitionResult>}
     * @memberof CompleteOnboardingResponse
     */
    definitionResults: Array<BusinessDefinitionResult>;
}

/**
 * Check if a given object implements the CompleteOnboardingResponse interface.
 */
export function instanceOfCompleteOnboardingResponse(value: object): value is CompleteOnboardingResponse {
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('templateResult' in value) || value['templateResult'] === undefined) return false;
    if (!('inviteResults' in value) || value['inviteResults'] === undefined) return false;
    if (!('definitionResults' in value) || value['definitionResults'] === undefined) return false;
    return true;
}

export function CompleteOnboardingResponseFromJSON(json: any): CompleteOnboardingResponse {
    return CompleteOnboardingResponseFromJSONTyped(json, false);
}

export function CompleteOnboardingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteOnboardingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workspace': WorkspaceFromJSON(json['workspace']),
        'user': UserDisplayFromJSON(json['user']),
        'templateResult': TemplateInstallResultFromJSON(json['templateResult']),
        'inviteResults': ((json['inviteResults'] as Array<any>).map(InviteResultFromJSON)),
        'definitionResults': ((json['definitionResults'] as Array<any>).map(BusinessDefinitionResultFromJSON)),
    };
}

export function CompleteOnboardingResponseToJSON(json: any): CompleteOnboardingResponse {
    return CompleteOnboardingResponseToJSONTyped(json, false);
}

export function CompleteOnboardingResponseToJSONTyped(value?: CompleteOnboardingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workspace': WorkspaceToJSON(value['workspace']),
        'user': UserDisplayToJSON(value['user']),
        'templateResult': TemplateInstallResultToJSON(value['templateResult']),
        'inviteResults': ((value['inviteResults'] as Array<any>).map(InviteResultToJSON)),
        'definitionResults': ((value['definitionResults'] as Array<any>).map(BusinessDefinitionResultToJSON)),
    };
}

