/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Path } from './Path';
import {
    instanceOfPath,
    PathFromJSONTyped,
    PathToJSON
} from './Path';
import type { Value } from './Value';
import {
    instanceOfValue,
    ValueFromJSONTyped,
    ValueToJSON
} from './Value';

/**
 * @type ConditionRight
 * 
 * @export
 */
export type ConditionRight = Path | Value;

export function ConditionRightFromJSON(json: any): ConditionRight {
    return ConditionRightFromJSONTyped(json, false);
}

export function ConditionRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConditionRight {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPath(json)) {
        return PathFromJSONTyped(json, true);
    }
    if (instanceOfValue(json)) {
        return ValueFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ConditionRightToJSON(json: any): any {
    return ConditionRightToJSONTyped(json, false);
}

export function ConditionRightToJSONTyped(value?: ConditionRight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPath(value)) {
        return PathToJSON(value as Path);
    }
    if (instanceOfValue(value)) {
        return ValueToJSON(value as Value);
    }
    return {};
}

