/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Information } from './Information';
import {
    InformationFromJSONTyped,
    InformationToJSON,
    instanceOfInformation
} from './Information';
import type { ReviewRequest } from './ReviewRequest';
import {
    instanceOfReviewRequest,
    ReviewRequestFromJSONTyped,
    ReviewRequestToJSON
} from './ReviewRequest';
import type { System } from './System';
import {
    instanceOfSystem,
    SystemFromJSONTyped,
    SystemToJSON
} from './System';

/**
 * @type CreateNotificationRequestContent
 * 
 * @export
 */
export type CreateNotificationRequestContent = Information | ReviewRequest | System;

export function CreateNotificationRequestContentFromJSON(json: any): CreateNotificationRequestContent {
    return CreateNotificationRequestContentFromJSONTyped(json, false);
}

export function CreateNotificationRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNotificationRequestContent {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfInformation(json)) {
        return InformationFromJSONTyped(json, true);
    }
    if (instanceOfReviewRequest(json)) {
        return ReviewRequestFromJSONTyped(json, true);
    }
    if (instanceOfSystem(json)) {
        return SystemFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateNotificationRequestContentToJSON(json: any): any {
    return CreateNotificationRequestContentToJSONTyped(json, false);
}

export function CreateNotificationRequestContentToJSONTyped(value?: CreateNotificationRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInformation(value)) {
        return InformationToJSON(value as Information);
    }
    if (instanceOfReviewRequest(value)) {
        return ReviewRequestToJSON(value as ReviewRequest);
    }
    if (instanceOfSystem(value)) {
        return SystemToJSON(value as System);
    }
    return {};
}

