/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DisplayName } from './DisplayName';
import {
    DisplayNameFromJSON,
    DisplayNameToJSON
} from './DisplayName';
import type { Icon } from './Icon';
import {
    IconFromJSON,
    IconToJSON
} from './Icon';
import type { LifecycleDomain } from './LifecycleDomain';
import {
    LifecycleDomainFromJSON,
    LifecycleDomainToJSON
} from './LifecycleDomain';
import type { SaveSemanticMetadataRequest } from './SaveSemanticMetadataRequest';
import {
    SaveSemanticMetadataRequestFromJSON,
    SaveSemanticMetadataRequestToJSON
} from './SaveSemanticMetadataRequest';
import type { SemanticGroup } from './SemanticGroup';
import {
    SemanticGroupFromJSON,
    SemanticGroupToJSON
} from './SemanticGroup';

/**
 * 
 * @export
 * @interface CreateEntityTypeRequest
 */
export interface CreateEntityTypeRequest {
    /**
     * 
     * @type {DisplayName}
     * @memberof CreateEntityTypeRequest
     */
    name: DisplayName;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityTypeRequest
     */
    key: string;
    /**
     * 
     * @type {Icon}
     * @memberof CreateEntityTypeRequest
     */
    icon: Icon;
    /**
     * 
     * @type {SemanticGroup}
     * @memberof CreateEntityTypeRequest
     */
    semanticGroup: SemanticGroup;
    /**
     * 
     * @type {LifecycleDomain}
     * @memberof CreateEntityTypeRequest
     */
    lifecycleDomain: LifecycleDomain;
    /**
     * 
     * @type {SaveSemanticMetadataRequest}
     * @memberof CreateEntityTypeRequest
     */
    semantics?: SaveSemanticMetadataRequest | null;
}



/**
 * Check if a given object implements the CreateEntityTypeRequest interface.
 */
export function instanceOfCreateEntityTypeRequest(value: object): value is CreateEntityTypeRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('semanticGroup' in value) || value['semanticGroup'] === undefined) return false;
    if (!('lifecycleDomain' in value) || value['lifecycleDomain'] === undefined) return false;
    return true;
}

export function CreateEntityTypeRequestFromJSON(json: any): CreateEntityTypeRequest {
    return CreateEntityTypeRequestFromJSONTyped(json, false);
}

export function CreateEntityTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEntityTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': DisplayNameFromJSON(json['name']),
        'key': json['key'],
        'icon': IconFromJSON(json['icon']),
        'semanticGroup': SemanticGroupFromJSON(json['semanticGroup']),
        'lifecycleDomain': LifecycleDomainFromJSON(json['lifecycleDomain']),
        'semantics': json['semantics'] == null ? undefined : SaveSemanticMetadataRequestFromJSON(json['semantics']),
    };
}

export function CreateEntityTypeRequestToJSON(json: any): CreateEntityTypeRequest {
    return CreateEntityTypeRequestToJSONTyped(json, false);
}

export function CreateEntityTypeRequestToJSONTyped(value?: CreateEntityTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': DisplayNameToJSON(value['name']),
        'key': value['key'],
        'icon': IconToJSON(value['icon']),
        'semanticGroup': SemanticGroupToJSON(value['semanticGroup']),
        'lifecycleDomain': LifecycleDomainToJSON(value['lifecycleDomain']),
        'semantics': SaveSemanticMetadataRequestToJSON(value['semantics']),
    };
}

