/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkspaceNote } from './WorkspaceNote';
import {
    WorkspaceNoteFromJSON,
    WorkspaceNoteToJSON
} from './WorkspaceNote';

/**
 * 
 * @export
 * @interface CursorPageWorkspaceNote
 */
export interface CursorPageWorkspaceNote {
    /**
     * 
     * @type {Array<WorkspaceNote>}
     * @memberof CursorPageWorkspaceNote
     */
    items: Array<WorkspaceNote>;
    /**
     * 
     * @type {string}
     * @memberof CursorPageWorkspaceNote
     */
    nextCursor?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CursorPageWorkspaceNote
     */
    totalCount?: number | null;
}

/**
 * Check if a given object implements the CursorPageWorkspaceNote interface.
 */
export function instanceOfCursorPageWorkspaceNote(value: object): value is CursorPageWorkspaceNote {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CursorPageWorkspaceNoteFromJSON(json: any): CursorPageWorkspaceNote {
    return CursorPageWorkspaceNoteFromJSONTyped(json, false);
}

export function CursorPageWorkspaceNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageWorkspaceNote {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WorkspaceNoteFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function CursorPageWorkspaceNoteToJSON(json: any): CursorPageWorkspaceNote {
    return CursorPageWorkspaceNoteToJSONTyped(json, false);
}

export function CursorPageWorkspaceNoteToJSONTyped(value?: CursorPageWorkspaceNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WorkspaceNoteToJSON)),
        'nextCursor': value['nextCursor'],
        'totalCount': value['totalCount'],
    };
}

