/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CursorIndexWarning } from './CursorIndexWarning';
import {
    CursorIndexWarningFromJSON,
    CursorIndexWarningToJSON
} from './CursorIndexWarning';
import type { PendingRelationship } from './PendingRelationship';
import {
    PendingRelationshipFromJSON,
    PendingRelationshipToJSON
} from './PendingRelationship';

/**
 * 
 * @export
 * @interface DataConnectorMappingSaveResponse
 */
export interface DataConnectorMappingSaveResponse {
    /**
     * 
     * @type {string}
     * @memberof DataConnectorMappingSaveResponse
     */
    entityTypeId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataConnectorMappingSaveResponse
     */
    relationshipsCreated: Array<string>;
    /**
     * 
     * @type {Array<PendingRelationship>}
     * @memberof DataConnectorMappingSaveResponse
     */
    pendingRelationships: Array<PendingRelationship>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataConnectorMappingSaveResponse
     */
    compositeFkSkipped: Array<string>;
    /**
     * 
     * @type {CursorIndexWarning}
     * @memberof DataConnectorMappingSaveResponse
     */
    cursorIndexWarning?: CursorIndexWarning | null;
}

/**
 * Check if a given object implements the DataConnectorMappingSaveResponse interface.
 */
export function instanceOfDataConnectorMappingSaveResponse(value: object): value is DataConnectorMappingSaveResponse {
    if (!('entityTypeId' in value) || value['entityTypeId'] === undefined) return false;
    if (!('relationshipsCreated' in value) || value['relationshipsCreated'] === undefined) return false;
    if (!('pendingRelationships' in value) || value['pendingRelationships'] === undefined) return false;
    if (!('compositeFkSkipped' in value) || value['compositeFkSkipped'] === undefined) return false;
    return true;
}

export function DataConnectorMappingSaveResponseFromJSON(json: any): DataConnectorMappingSaveResponse {
    return DataConnectorMappingSaveResponseFromJSONTyped(json, false);
}

export function DataConnectorMappingSaveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataConnectorMappingSaveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityTypeId': json['entityTypeId'],
        'relationshipsCreated': json['relationshipsCreated'],
        'pendingRelationships': ((json['pendingRelationships'] as Array<any>).map(PendingRelationshipFromJSON)),
        'compositeFkSkipped': json['compositeFkSkipped'],
        'cursorIndexWarning': json['cursorIndexWarning'] == null ? undefined : CursorIndexWarningFromJSON(json['cursorIndexWarning']),
    };
}

export function DataConnectorMappingSaveResponseToJSON(json: any): DataConnectorMappingSaveResponse {
    return DataConnectorMappingSaveResponseToJSONTyped(json, false);
}

export function DataConnectorMappingSaveResponseToJSONTyped(value?: DataConnectorMappingSaveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityTypeId': value['entityTypeId'],
        'relationshipsCreated': value['relationshipsCreated'],
        'pendingRelationships': ((value['pendingRelationships'] as Array<any>).map(PendingRelationshipToJSON)),
        'compositeFkSkipped': value['compositeFkSkipped'],
        'cursorIndexWarning': CursorIndexWarningToJSON(value['cursorIndexWarning']),
    };
}

