/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { type Dynamic, DynamicFromJSONTyped, DynamicToJSONTyped } from './Dynamic';
import { type Static, StaticFromJSONTyped, StaticToJSONTyped } from './Static';
/**
 * 
 * @export
 * @interface DefaultValue
 */
export interface DefaultValue {
    /**
     * 
     * @type {string}
     * @memberof DefaultValue
     */
    type: string;
}

/**
 * Check if a given object implements the DefaultValue interface.
 */
export function instanceOfDefaultValue(value: object): value is DefaultValue {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function DefaultValueFromJSON(json: any): DefaultValue {
    return DefaultValueFromJSONTyped(json, false);
}

export function DefaultValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultValue {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'Dynamic') {
            return DynamicFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['type'] === 'Static') {
            return StaticFromJSONTyped(json, ignoreDiscriminator);
        }

    }
    return {
        
        'type': json['type'],
    };
}

export function DefaultValueToJSON(json: any): DefaultValue {
    return DefaultValueToJSONTyped(json, false);
}

export function DefaultValueToJSONTyped(value?: DefaultValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['type']) {
            case 'Dynamic':
                return DynamicToJSONTyped(value as Dynamic, ignoreDiscriminator);
            case 'Static':
                return StaticToJSONTyped(value as Static, ignoreDiscriminator);
            default:
                return value;
        }
    }

    return {
        
        'type': value['type'],
    };
}

