/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityType } from './EntityType';
import {
    EntityTypeFromJSON,
    EntityTypeFromJSONTyped,
    EntityTypeToJSON,
    EntityTypeToJSONTyped,
} from './EntityType';
import type { SemanticMetadataBundle } from './SemanticMetadataBundle';
import {
    SemanticMetadataBundleFromJSON,
    SemanticMetadataBundleFromJSONTyped,
    SemanticMetadataBundleToJSON,
    SemanticMetadataBundleToJSONTyped,
} from './SemanticMetadataBundle';
import type { RelationshipDefinition } from './RelationshipDefinition';
import {
    RelationshipDefinitionFromJSON,
    RelationshipDefinitionFromJSONTyped,
    RelationshipDefinitionToJSON,
    RelationshipDefinitionToJSONTyped,
} from './RelationshipDefinition';

/**
 * 
 * @export
 * @interface EntityTypeWithSemanticsResponse
 */
export interface EntityTypeWithSemanticsResponse {
    /**
     * 
     * @type {EntityType}
     * @memberof EntityTypeWithSemanticsResponse
     */
    entityType: EntityType;
    /**
     * 
     * @type {Array<RelationshipDefinition>}
     * @memberof EntityTypeWithSemanticsResponse
     */
    relationships: Array<RelationshipDefinition>;
    /**
     * 
     * @type {SemanticMetadataBundle}
     * @memberof EntityTypeWithSemanticsResponse
     */
    semantics?: SemanticMetadataBundle;
}

/**
 * Check if a given object implements the EntityTypeWithSemanticsResponse interface.
 */
export function instanceOfEntityTypeWithSemanticsResponse(value: object): value is EntityTypeWithSemanticsResponse {
    if (!('entityType' in value) || value['entityType'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function EntityTypeWithSemanticsResponseFromJSON(json: any): EntityTypeWithSemanticsResponse {
    return EntityTypeWithSemanticsResponseFromJSONTyped(json, false);
}

export function EntityTypeWithSemanticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityTypeWithSemanticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityType': EntityTypeFromJSON(json['entityType']),
        'relationships': ((json['relationships'] as Array<any>).map(RelationshipDefinitionFromJSON)),
        'semantics': json['semantics'] == null ? undefined : SemanticMetadataBundleFromJSON(json['semantics']),
    };
}

export function EntityTypeWithSemanticsResponseToJSON(json: any): EntityTypeWithSemanticsResponse {
    return EntityTypeWithSemanticsResponseToJSONTyped(json, false);
}

export function EntityTypeWithSemanticsResponseToJSONTyped(value?: EntityTypeWithSemanticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityType': EntityTypeToJSON(value['entityType']),
        'relationships': ((value['relationships'] as Array<any>).map(RelationshipDefinitionToJSON)),
        'semantics': SemanticMetadataBundleToJSON(value['semantics']),
    };
}

