/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Icon } from './Icon';
import {
    IconFromJSON,
    IconFromJSONTyped,
    IconToJSON,
    IconToJSONTyped,
} from './Icon';
import type { RelationshipDirection } from './RelationshipDirection';
import {
    RelationshipDirectionFromJSON,
    RelationshipDirectionToJSON,
} from './RelationshipDirection';
import type { SystemRelationshipType } from './SystemRelationshipType';
import {
    SystemRelationshipTypeFromJSON,
    SystemRelationshipTypeToJSON,
} from './SystemRelationshipType';

/**
 * 
 * @export
 * @interface EntityLink
 */
export interface EntityLink {
    /**
     * 
     * @type {string}
     * @memberof EntityLink
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EntityLink
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof EntityLink
     */
    definitionId: string;
    /**
     * 
     * @type {string}
     * @memberof EntityLink
     */
    sourceEntityId: string;
    /**
     * 
     * @type {Icon}
     * @memberof EntityLink
     */
    icon: Icon;
    /**
     * 
     * @type {string}
     * @memberof EntityLink
     */
    key: string;
    /**
     *
     * @type {string}
     * @memberof EntityLink
     */
    label: string;
    /**
     *
     * @type {RelationshipDirection}
     * @memberof EntityLink
     */
    direction: RelationshipDirection;
    /**
     *
     * @type {SystemRelationshipType}
     * @memberof EntityLink
     */
    systemType?: SystemRelationshipType | null;
}

/**
 * Check if a given object implements the EntityLink interface.
 */
export function instanceOfEntityLink(value: object): value is EntityLink {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspaceId' in value) || value['workspaceId'] === undefined) return false;
    if (!('definitionId' in value) || value['definitionId'] === undefined) return false;
    if (!('sourceEntityId' in value) || value['sourceEntityId'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    return true;
}

export function EntityLinkFromJSON(json: any): EntityLink {
    return EntityLinkFromJSONTyped(json, false);
}

export function EntityLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityLink {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'workspaceId': json['workspaceId'],
        'definitionId': json['definitionId'],
        'sourceEntityId': json['sourceEntityId'],
        'icon': IconFromJSON(json['icon']),
        'key': json['key'],
        'label': json['label'],
        'direction': RelationshipDirectionFromJSON(json['direction']),
        'systemType': json['systemType'] == null ? undefined : SystemRelationshipTypeFromJSON(json['systemType']),
    };
}

export function EntityLinkToJSON(json: any): EntityLink {
    return EntityLinkToJSONTyped(json, false);
}

export function EntityLinkToJSONTyped(value?: EntityLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'workspaceId': value['workspaceId'],
        'definitionId': value['definitionId'],
        'sourceEntityId': value['sourceEntityId'],
        'icon': IconToJSON(value['icon']),
        'key': value['key'],
        'label': value['label'],
        'direction': RelationshipDirectionToJSON(value['direction']),
        'systemType': SystemRelationshipTypeToJSON(value['systemType']),
    };
}

