/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { QueryFilter } from './QueryFilter';
import {
    QueryFilterFromJSON,
    QueryFilterToJSON
} from './QueryFilter';
import type { QueryPagination } from './QueryPagination';
import {
    QueryPaginationFromJSON,
    QueryPaginationToJSON
} from './QueryPagination';
import type { QueryProjection } from './QueryProjection';
import {
    QueryProjectionFromJSON,
    QueryProjectionToJSON
} from './QueryProjection';

/**
 * Request body for querying entities with filtering, pagination, and sorting
 * @export
 * @interface EntityQueryRequest
 */
export interface EntityQueryRequest {
    /**
     * 
     * @type {QueryFilter}
     * @memberof EntityQueryRequest
     */
    filter?: QueryFilter | null;
    /**
     * 
     * @type {QueryPagination}
     * @memberof EntityQueryRequest
     */
    pagination: QueryPagination | null;
    /**
     * 
     * @type {QueryProjection}
     * @memberof EntityQueryRequest
     */
    projection?: QueryProjection | null;
    /**
     * Whether to include totalCount in the response. Set to false for scroll-pagination requests where the frontend already has the count from the initial load.
     * @type {boolean}
     * @memberof EntityQueryRequest
     */
    includeCount?: boolean;
    /**
     * Maximum relationship traversal depth for nested filters (1-10).
     * @type {number}
     * @memberof EntityQueryRequest
     */
    maxDepth: number;
}

/**
 * Check if a given object implements the EntityQueryRequest interface.
 */
export function instanceOfEntityQueryRequest(value: object): value is EntityQueryRequest {
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('maxDepth' in value) || value['maxDepth'] === undefined) return false;
    return true;
}

export function EntityQueryRequestFromJSON(json: any): EntityQueryRequest {
    return EntityQueryRequestFromJSONTyped(json, false);
}

export function EntityQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': json['filter'] == null ? undefined : QueryFilterFromJSON(json['filter']),
        'pagination': QueryPaginationFromJSON(json['pagination']),
        'projection': json['projection'] == null ? undefined : QueryProjectionFromJSON(json['projection']),
        'includeCount': json['includeCount'] == null ? undefined : json['includeCount'],
        'maxDepth': json['maxDepth'],
    };
}

export function EntityQueryRequestToJSON(json: any): EntityQueryRequest {
    return EntityQueryRequestToJSONTyped(json, false);
}

export function EntityQueryRequestToJSONTyped(value?: EntityQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter': QueryFilterToJSON(value['filter']),
        'pagination': QueryPaginationToJSON(value['pagination']),
        'projection': QueryProjectionToJSON(value['projection']),
        'includeCount': value['includeCount'],
        'maxDepth': value['maxDepth'],
    };
}

