/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RelationshipFilter } from './RelationshipFilter';

/**
 * Entity has at least one related entity.
 * @export
 * @interface Exists
 */
export interface Exists extends RelationshipFilter {
}



/**
 * Check if a given object implements the Exists interface.
 */
export function instanceOfExists(value: object): value is Exists {
    return true;
}

export function ExistsFromJSON(json: any): Exists {
    return ExistsFromJSONTyped(json, false);
}

export function ExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Exists {
    return json;
}

export function ExistsToJSON(json: any): Exists {
    return ExistsToJSONTyped(json, false);
}

export function ExistsToJSONTyped(value?: Exists | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

