/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlockFormWidgetType } from './BlockFormWidgetType';
import {
    BlockFormWidgetTypeFromJSON,
    BlockFormWidgetTypeToJSON
} from './BlockFormWidgetType';
import type { Option } from './Option';
import {
    OptionFromJSON,
    OptionToJSON
} from './Option';

/**
 * 
 * @export
 * @interface FormWidgetConfig
 */
export interface FormWidgetConfig {
    /**
     * 
     * @type {BlockFormWidgetType}
     * @memberof FormWidgetConfig
     */
    type: BlockFormWidgetType;
    /**
     * 
     * @type {string}
     * @memberof FormWidgetConfig
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof FormWidgetConfig
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FormWidgetConfig
     */
    tooltip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FormWidgetConfig
     */
    placeholder?: string | null;
    /**
     * 
     * @type {Array<Option>}
     * @memberof FormWidgetConfig
     */
    options?: Array<Option> | null;
}



/**
 * Check if a given object implements the FormWidgetConfig interface.
 */
export function instanceOfFormWidgetConfig(value: object): value is FormWidgetConfig {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function FormWidgetConfigFromJSON(json: any): FormWidgetConfig {
    return FormWidgetConfigFromJSONTyped(json, false);
}

export function FormWidgetConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormWidgetConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'type': BlockFormWidgetTypeFromJSON(json['type']),
        'label': json['label'],
        'description': json['description'] == null ? undefined : json['description'],
        'tooltip': json['tooltip'] == null ? undefined : json['tooltip'],
        'placeholder': json['placeholder'] == null ? undefined : json['placeholder'],
        'options': json['options'] == null ? undefined : ((json['options'] as Array<any>).map(OptionFromJSON)),
    };
}

export function FormWidgetConfigToJSON(json: any): FormWidgetConfig {
    return FormWidgetConfigToJSONTyped(json, false);
}

export function FormWidgetConfigToJSONTyped(value?: FormWidgetConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': BlockFormWidgetTypeToJSON(value['type']),
        'label': value['label'],
        'description': value['description'],
        'tooltip': value['tooltip'],
        'placeholder': value['placeholder'],
        'options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(OptionToJSON)),
    };
}

