/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IconColour } from './IconColour';
import {
    IconColourFromJSON,
    IconColourToJSON
} from './IconColour';
import type { IconType } from './IconType';
import {
    IconTypeFromJSON,
    IconTypeToJSON
} from './IconType';

/**
 * 
 * @export
 * @interface Icon
 */
export interface Icon {
    /**
     * 
     * @type {IconType}
     * @memberof Icon
     */
    type: IconType;
    /**
     * 
     * @type {IconColour}
     * @memberof Icon
     */
    colour: IconColour;
}



/**
 * Check if a given object implements the Icon interface.
 */
export function instanceOfIcon(value: object): value is Icon {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('colour' in value) || value['colour'] === undefined) return false;
    return true;
}

export function IconFromJSON(json: any): Icon {
    return IconFromJSONTyped(json, false);
}

export function IconFromJSONTyped(json: any, ignoreDiscriminator: boolean): Icon {
    if (json == null) {
        return json;
    }
    return {
        
        'type': IconTypeFromJSON(json['type']),
        'colour': IconColourFromJSON(json['colour']),
    };
}

export function IconToJSON(json: any): Icon {
    return IconToJSONTyped(json, false);
}

export function IconToJSONTyped(value?: Icon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': IconTypeToJSON(value['type']),
        'colour': IconColourToJSON(value['colour']),
    };
}

