/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { QueryFilter } from './QueryFilter';
import {
    QueryFilterFromJSONTyped,
    QueryFilterToJSONTyped
} from './QueryFilter';
import type { RelationshipFilter } from './RelationshipFilter';
import {
    RelationshipFilterFromJSON,
    RelationshipFilterToJSON
} from './RelationshipFilter';

/**
 * Filter by any relationship across all definitions.
 * @export
 * @interface IsRelatedTo
 */
export interface IsRelatedTo extends QueryFilter {
    /**
     * 
     * @type {RelationshipFilter}
     * @memberof IsRelatedTo
     */
    condition: RelationshipFilter;
}



/**
 * Check if a given object implements the IsRelatedTo interface.
 */
export function instanceOfIsRelatedTo(value: object): value is IsRelatedTo {
    if (!('condition' in value) || value['condition'] === undefined) return false;
    return true;
}

export function IsRelatedToFromJSON(json: any): IsRelatedTo {
    return IsRelatedToFromJSONTyped(json, false);
}

export function IsRelatedToFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsRelatedTo {
    if (json == null) {
        return json;
    }
    return {
        ...QueryFilterFromJSONTyped(json, true),
        'condition': RelationshipFilterFromJSON(json['condition']),
    };
}

export function IsRelatedToToJSON(json: any): IsRelatedTo {
    return IsRelatedToToJSONTyped(json, false);
}

export function IsRelatedToToJSONTyped(value?: IsRelatedTo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...QueryFilterToJSONTyped(value, true),
        'condition': RelationshipFilterToJSON(value['condition']),
    };
}

