/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FilterValue } from './FilterValue';
import {
    FilterValueFromJSONTyped,
    FilterValueToJSONTyped
} from './FilterValue';

/**
 * Literal value for comparison.
 * @export
 * @interface Literal
 */
export interface Literal extends FilterValue {
    /**
     * 
     * @type {object}
     * @memberof Literal
     */
    value?: object | null;
}

/**
 * Check if a given object implements the Literal interface.
 */
export function instanceOfLiteral(value: object): value is Literal {
    return true;
}

export function LiteralFromJSON(json: any): Literal {
    return LiteralFromJSONTyped(json, false);
}

export function LiteralFromJSONTyped(json: any, ignoreDiscriminator: boolean): Literal {
    if (json == null) {
        return json;
    }
    return {
        ...FilterValueFromJSONTyped(json, true),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function LiteralToJSON(json: any): Literal {
    return LiteralToJSONTyped(json, false);
}

export function LiteralToJSONTyped(value?: Literal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...FilterValueToJSONTyped(value, true),
        'value': value['value'],
    };
}

