/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ContentNode } from './ContentNode';
import {
    ContentNodeFromJSONTyped,
    ContentNodeToJSON,
    instanceOfContentNode
} from './ContentNode';
import type { ReferenceNode } from './ReferenceNode';
import {
    instanceOfReferenceNode,
    ReferenceNodeFromJSONTyped,
    ReferenceNodeToJSON
} from './ReferenceNode';

/**
 * @type Node
 * 
 * @export
 */
export type Node = ContentNode | ReferenceNode;

export function NodeFromJSON(json: any): Node {
    return NodeFromJSONTyped(json, false);
}

export function NodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Node {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfContentNode(json)) {
        return ContentNodeFromJSONTyped(json, true);
    }
    if (instanceOfReferenceNode(json)) {
        return ReferenceNodeFromJSONTyped(json, true);
    }
    return {} as any;
}

export function NodeToJSON(json: any): any {
    return NodeToJSONTyped(json, false);
}

export function NodeToJSONTyped(value?: Node | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfContentNode(value)) {
        return ContentNodeToJSON(value as ContentNode);
    }
    if (instanceOfReferenceNode(value)) {
        return ReferenceNodeToJSON(value as ReferenceNode);
    }
    return {};
}

