/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RelationshipFilter } from './RelationshipFilter';

/**
 * Entity has no related entities.
 * @export
 * @interface NotExists
 */
export interface NotExists extends RelationshipFilter {
}



/**
 * Check if a given object implements the NotExists interface.
 */
export function instanceOfNotExists(value: object): value is NotExists {
    return true;
}

export function NotExistsFromJSON(json: any): NotExists {
    return NotExistsFromJSONTyped(json, false);
}

export function NotExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotExists {
    return json;
}

export function NotExistsToJSON(json: any): NotExists {
    return NotExistsToJSONTyped(json, false);
}

export function NotExistsToJSONTyped(value?: NotExists | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

