/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkspaceRoles } from './WorkspaceRoles';
import {
    WorkspaceRolesFromJSON,
    WorkspaceRolesToJSON
} from './WorkspaceRoles';

/**
 * 
 * @export
 * @interface OnboardingInvite
 */
export interface OnboardingInvite {
    /**
     * 
     * @type {string}
     * @memberof OnboardingInvite
     */
    email: string;
    /**
     * 
     * @type {WorkspaceRoles}
     * @memberof OnboardingInvite
     */
    role: WorkspaceRoles;
}



/**
 * Check if a given object implements the OnboardingInvite interface.
 */
export function instanceOfOnboardingInvite(value: object): value is OnboardingInvite {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function OnboardingInviteFromJSON(json: any): OnboardingInvite {
    return OnboardingInviteFromJSONTyped(json, false);
}

export function OnboardingInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingInvite {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': WorkspaceRolesFromJSON(json['role']),
    };
}

export function OnboardingInviteToJSON(json: any): OnboardingInvite {
    return OnboardingInviteToJSONTyped(json, false);
}

export function OnboardingInviteToJSONTyped(value?: OnboardingInvite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': WorkspaceRolesToJSON(value['role']),
    };
}

