/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { And } from './And';
import {
    AndFromJSONTyped,
    AndToJSON
} from './And';
import type { Attribute } from './Attribute';
import {
    AttributeFromJSONTyped,
    AttributeToJSON
} from './Attribute';
import type { IsRelatedTo } from './IsRelatedTo';
import {
    IsRelatedToFromJSONTyped,
    IsRelatedToToJSON
} from './IsRelatedTo';
import type { Or } from './Or';
import {
    OrFromJSONTyped,
    OrToJSON
} from './Or';
import type { Relationship } from './Relationship';
import {
    RelationshipFromJSONTyped,
    RelationshipToJSON
} from './Relationship';

/**
 * @type QueryFilter
 * Filter expression for querying entities.
 * @export
 */
export type QueryFilter = { type: 'And' } & And | { type: 'Attribute' } & Attribute | { type: 'IsRelatedTo' } & IsRelatedTo | { type: 'Or' } & Or | { type: 'Relationship' } & Relationship;

export function QueryFilterFromJSON(json: any): QueryFilter {
    return QueryFilterFromJSONTyped(json, false);
}

export function QueryFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryFilter {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'And':
            return Object.assign({}, AndFromJSONTyped(json, true), { type: 'And' } as const);
        case 'Attribute':
            return Object.assign({}, AttributeFromJSONTyped(json, true), { type: 'Attribute' } as const);
        case 'IsRelatedTo':
            return Object.assign({}, IsRelatedToFromJSONTyped(json, true), { type: 'IsRelatedTo' } as const);
        case 'Or':
            return Object.assign({}, OrFromJSONTyped(json, true), { type: 'Or' } as const);
        case 'Relationship':
            return Object.assign({}, RelationshipFromJSONTyped(json, true), { type: 'Relationship' } as const);
        default:
            return json;
    }
}

export function QueryFilterToJSON(json: any): any {
    return QueryFilterToJSONTyped(json, false);
}

export function QueryFilterToJSONTyped(value?: QueryFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'And':
            return Object.assign({}, AndToJSON(value), { type: 'And' } as const);
        case 'Attribute':
            return Object.assign({}, AttributeToJSON(value), { type: 'Attribute' } as const);
        case 'IsRelatedTo':
            return Object.assign({}, IsRelatedToToJSON(value), { type: 'IsRelatedTo' } as const);
        case 'Or':
            return Object.assign({}, OrToJSON(value), { type: 'Or' } as const);
        case 'Relationship':
            return Object.assign({}, RelationshipToJSON(value), { type: 'Relationship' } as const);
        default:
            return value;
    }
}

