/* tslint:disable */
/* eslint-disable */
/**
 * Riven Core API
 * API documentation for Riven Core services.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum RelationshipDirection {
    Forward = 'FORWARD',
    Inverse = 'INVERSE'
}


export function instanceOfRelationshipDirection(value: any): boolean {
    for (const key in RelationshipDirection) {
        if (Object.prototype.hasOwnProperty.call(RelationshipDirection, key)) {
            if (RelationshipDirection[key as keyof typeof RelationshipDirection] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RelationshipDirectionFromJSON(json: any): RelationshipDirection {
    return RelationshipDirectionFromJSONTyped(json, false);
}

export function RelationshipDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipDirection {
    return json as RelationshipDirection;
}

export function RelationshipDirectionToJSON(value?: RelationshipDirection | null): any {
    return value as any;
}

export function RelationshipDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): RelationshipDirection {
    return value as RelationshipDirection;
}
