/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NodeType } from './NodeType';
import {
    NodeTypeFromJSON,
    NodeTypeToJSON
} from './NodeType';
import type { RenderType } from './RenderType';
import {
    RenderTypeFromJSON,
    RenderTypeToJSON
} from './RenderType';

/**
 * 
 * @export
 * @interface RenderContent
 */
export interface RenderContent {
    /**
     * 
     * @type {string}
     * @memberof RenderContent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RenderContent
     */
    key: string;
    /**
     * 
     * @type {RenderType}
     * @memberof RenderContent
     */
    renderType: RenderType;
    /**
     * 
     * @type {NodeType}
     * @memberof RenderContent
     */
    blockType: NodeType;
}



/**
 * Check if a given object implements the RenderContent interface.
 */
export function instanceOfRenderContent(value: object): value is RenderContent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('renderType' in value) || value['renderType'] === undefined) return false;
    if (!('blockType' in value) || value['blockType'] === undefined) return false;
    return true;
}

export function RenderContentFromJSON(json: any): RenderContent {
    return RenderContentFromJSONTyped(json, false);
}

export function RenderContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderContent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'renderType': RenderTypeFromJSON(json['renderType']),
        'blockType': NodeTypeFromJSON(json['blockType']),
    };
}

export function RenderContentToJSON(json: any): RenderContent {
    return RenderContentToJSONTyped(json, false);
}

export function RenderContentToJSONTyped(value?: RenderContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'renderType': RenderTypeToJSON(value['renderType']),
        'blockType': NodeTypeToJSON(value['blockType']),
    };
}

