/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowActionConfig } from './WorkflowActionConfig';
import {
    instanceOfWorkflowActionConfig,
    WorkflowActionConfigFromJSONTyped,
    WorkflowActionConfigToJSON
} from './WorkflowActionConfig';
import type { WorkflowControlConfig } from './WorkflowControlConfig';
import {
    instanceOfWorkflowControlConfig,
    WorkflowControlConfigFromJSONTyped,
    WorkflowControlConfigToJSON
} from './WorkflowControlConfig';
import type { WorkflowFunctionConfig } from './WorkflowFunctionConfig';
import {
    instanceOfWorkflowFunctionConfig,
    WorkflowFunctionConfigFromJSONTyped,
    WorkflowFunctionConfigToJSON
} from './WorkflowFunctionConfig';
import type { WorkflowParseConfig } from './WorkflowParseConfig';
import {
    instanceOfWorkflowParseConfig,
    WorkflowParseConfigFromJSONTyped,
    WorkflowParseConfigToJSON
} from './WorkflowParseConfig';
import type { WorkflowTriggerConfig } from './WorkflowTriggerConfig';
import {
    instanceOfWorkflowTriggerConfig,
    WorkflowTriggerConfigFromJSONTyped,
    WorkflowTriggerConfigToJSON
} from './WorkflowTriggerConfig';
import type { WorkflowUtilityConfig } from './WorkflowUtilityConfig';
import {
    instanceOfWorkflowUtilityConfig,
    WorkflowUtilityConfigFromJSONTyped,
    WorkflowUtilityConfigToJSON
} from './WorkflowUtilityConfig';

/**
 * @type SaveWorkflowNodeRequestConfig
 * 
 * @export
 */
export type SaveWorkflowNodeRequestConfig = WorkflowActionConfig | WorkflowControlConfig | WorkflowFunctionConfig | WorkflowParseConfig | WorkflowTriggerConfig | WorkflowUtilityConfig;

export function SaveWorkflowNodeRequestConfigFromJSON(json: any): SaveWorkflowNodeRequestConfig {
    return SaveWorkflowNodeRequestConfigFromJSONTyped(json, false);
}

export function SaveWorkflowNodeRequestConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveWorkflowNodeRequestConfig {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfWorkflowActionConfig(json)) {
        return WorkflowActionConfigFromJSONTyped(json, true);
    }
    if (instanceOfWorkflowControlConfig(json)) {
        return WorkflowControlConfigFromJSONTyped(json, true);
    }
    if (instanceOfWorkflowFunctionConfig(json)) {
        return WorkflowFunctionConfigFromJSONTyped(json, true);
    }
    if (instanceOfWorkflowParseConfig(json)) {
        return WorkflowParseConfigFromJSONTyped(json, true);
    }
    if (instanceOfWorkflowTriggerConfig(json)) {
        return WorkflowTriggerConfigFromJSONTyped(json, true);
    }
    if (instanceOfWorkflowUtilityConfig(json)) {
        return WorkflowUtilityConfigFromJSONTyped(json, true);
    }
    return {} as any;
}

export function SaveWorkflowNodeRequestConfigToJSON(json: any): any {
    return SaveWorkflowNodeRequestConfigToJSONTyped(json, false);
}

export function SaveWorkflowNodeRequestConfigToJSONTyped(value?: SaveWorkflowNodeRequestConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfWorkflowActionConfig(value)) {
        return WorkflowActionConfigToJSON(value as WorkflowActionConfig);
    }
    if (instanceOfWorkflowControlConfig(value)) {
        return WorkflowControlConfigToJSON(value as WorkflowControlConfig);
    }
    if (instanceOfWorkflowFunctionConfig(value)) {
        return WorkflowFunctionConfigToJSON(value as WorkflowFunctionConfig);
    }
    if (instanceOfWorkflowParseConfig(value)) {
        return WorkflowParseConfigToJSON(value as WorkflowParseConfig);
    }
    if (instanceOfWorkflowTriggerConfig(value)) {
        return WorkflowTriggerConfigToJSON(value as WorkflowTriggerConfig);
    }
    if (instanceOfWorkflowUtilityConfig(value)) {
        return WorkflowUtilityConfigToJSON(value as WorkflowUtilityConfig);
    }
    return {};
}

