/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EntityRelationshipCardinality } from './EntityRelationshipCardinality';
import {
    EntityRelationshipCardinalityFromJSON,
    EntityRelationshipCardinalityToJSON
} from './EntityRelationshipCardinality';
import type { EntityTypeRequestDefinition } from './EntityTypeRequestDefinition';
import {
    EntityTypeRequestDefinitionFromJSON,
    EntityTypeRequestDefinitionToJSON
} from './EntityTypeRequestDefinition';
import type { IconColour } from './IconColour';
import {
    IconColourFromJSON,
    IconColourToJSON
} from './IconColour';
import type { IconType } from './IconType';
import {
    IconTypeFromJSON,
    IconTypeToJSON
} from './IconType';
import type { SaveSemanticMetadataRequest } from './SaveSemanticMetadataRequest';
import {
    SaveSemanticMetadataRequestFromJSON,
    SaveSemanticMetadataRequestToJSON
} from './SaveSemanticMetadataRequest';
import type { SaveTargetRuleRequest } from './SaveTargetRuleRequest';
import {
    SaveTargetRuleRequestFromJSON,
    SaveTargetRuleRequestToJSON
} from './SaveTargetRuleRequest';
import type { SchemaUUID } from './SchemaUUID';
import {
    SchemaUUIDFromJSON,
    SchemaUUIDToJSON
} from './SchemaUUID';

/**
 * Request to save a relationship definition for an entity type
 * @export
 * @interface SaveRelationshipDefinitionRequest
 */
export interface SaveRelationshipDefinitionRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveRelationshipDefinitionRequest
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof SaveRelationshipDefinitionRequest
     */
    id: string | null;
    /**
     * 
     * @type {EntityTypeRequestDefinition}
     * @memberof SaveRelationshipDefinitionRequest
     */
    type: EntityTypeRequestDefinition;
    /**
     * 
     * @type {SchemaUUID}
     * @memberof SaveRelationshipDefinitionRequest
     */
    schema: SchemaUUID;
    /**
     * 
     * @type {SaveSemanticMetadataRequest}
     * @memberof SaveRelationshipDefinitionRequest
     */
    semantics?: SaveSemanticMetadataRequest | null;
    /**
     * 
     * @type {string}
     * @memberof SaveRelationshipDefinitionRequest
     */
    name: string;
    /**
     * 
     * @type {IconType}
     * @memberof SaveRelationshipDefinitionRequest
     */
    iconType?: IconType | null;
    /**
     * 
     * @type {IconColour}
     * @memberof SaveRelationshipDefinitionRequest
     */
    iconColour?: IconColour | null;
    /**
     * 
     * @type {EntityRelationshipCardinality}
     * @memberof SaveRelationshipDefinitionRequest
     */
    cardinalityDefault: EntityRelationshipCardinality;
    /**
     * 
     * @type {Array<SaveTargetRuleRequest>}
     * @memberof SaveRelationshipDefinitionRequest
     */
    targetRules: Array<SaveTargetRuleRequest>;
}



/**
 * Check if a given object implements the SaveRelationshipDefinitionRequest interface.
 */
export function instanceOfSaveRelationshipDefinitionRequest(value: object): value is SaveRelationshipDefinitionRequest {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('cardinalityDefault' in value) || value['cardinalityDefault'] === undefined) return false;
    if (!('targetRules' in value) || value['targetRules'] === undefined) return false;
    return true;
}

export function SaveRelationshipDefinitionRequestFromJSON(json: any): SaveRelationshipDefinitionRequest {
    return SaveRelationshipDefinitionRequestFromJSONTyped(json, false);
}

export function SaveRelationshipDefinitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveRelationshipDefinitionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'id': json['id'],
        'type': EntityTypeRequestDefinitionFromJSON(json['type']),
        'schema': SchemaUUIDFromJSON(json['schema']),
        'semantics': json['semantics'] == null ? undefined : SaveSemanticMetadataRequestFromJSON(json['semantics']),
        'name': json['name'],
        'iconType': json['iconType'] == null ? undefined : IconTypeFromJSON(json['iconType']),
        'iconColour': json['iconColour'] == null ? undefined : IconColourFromJSON(json['iconColour']),
        'cardinalityDefault': EntityRelationshipCardinalityFromJSON(json['cardinalityDefault']),
        'targetRules': ((json['targetRules'] as Array<any>).map(SaveTargetRuleRequestFromJSON)),
    };
}

export function SaveRelationshipDefinitionRequestToJSON(json: any): SaveRelationshipDefinitionRequest {
    return SaveRelationshipDefinitionRequestToJSONTyped(json, false);
}

export function SaveRelationshipDefinitionRequestToJSONTyped(value?: SaveRelationshipDefinitionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'id': value['id'],
        'type': EntityTypeRequestDefinitionToJSON(value['type']),
        'schema': SchemaUUIDToJSON(value['schema']),
        'semantics': SaveSemanticMetadataRequestToJSON(value['semantics']),
        'name': value['name'],
        'iconType': IconTypeToJSON(value['iconType']),
        'iconColour': IconColourToJSON(value['iconColour']),
        'cardinalityDefault': EntityRelationshipCardinalityToJSON(value['cardinalityDefault']),
        'targetRules': ((value['targetRules'] as Array<any>).map(SaveTargetRuleRequestToJSON)),
    };
}

