/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowDefinition } from './WorkflowDefinition';
import {
    WorkflowDefinitionFromJSON,
    WorkflowDefinitionToJSON
} from './WorkflowDefinition';

/**
 * 
 * @export
 * @interface SaveWorkflowDefinitionResponse
 */
export interface SaveWorkflowDefinitionResponse {
    /**
     * 
     * @type {WorkflowDefinition}
     * @memberof SaveWorkflowDefinitionResponse
     */
    definition?: WorkflowDefinition | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SaveWorkflowDefinitionResponse
     */
    errors?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SaveWorkflowDefinitionResponse
     */
    created: boolean;
}

/**
 * Check if a given object implements the SaveWorkflowDefinitionResponse interface.
 */
export function instanceOfSaveWorkflowDefinitionResponse(value: object): value is SaveWorkflowDefinitionResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function SaveWorkflowDefinitionResponseFromJSON(json: any): SaveWorkflowDefinitionResponse {
    return SaveWorkflowDefinitionResponseFromJSONTyped(json, false);
}

export function SaveWorkflowDefinitionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveWorkflowDefinitionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'definition': json['definition'] == null ? undefined : WorkflowDefinitionFromJSON(json['definition']),
        'errors': json['errors'] == null ? undefined : json['errors'],
        'created': json['created'],
    };
}

export function SaveWorkflowDefinitionResponseToJSON(json: any): SaveWorkflowDefinitionResponse {
    return SaveWorkflowDefinitionResponseToJSONTyped(json, false);
}

export function SaveWorkflowDefinitionResponseToJSONTyped(value?: SaveWorkflowDefinitionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'definition': WorkflowDefinitionToJSON(value['definition']),
        'errors': value['errors'],
        'created': value['created'],
    };
}

