/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityAttributeRequest } from './EntityAttributeRequest';
import {
    EntityAttributeRequestFromJSON,
    EntityAttributeRequestToJSON
} from './EntityAttributeRequest';
import type { Icon } from './Icon';
import {
    IconFromJSON,
    IconToJSON
} from './Icon';

/**
 * 
 * @export
 * @interface SaveEntityRequest
 */
export interface SaveEntityRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveEntityRequest
     */
    id?: string | null;
    /**
     * 
     * @type {{ [key: string]: EntityAttributeRequest; }}
     * @memberof SaveEntityRequest
     */
    payload: { [key: string]: EntityAttributeRequest; };
    /**
     * 
     * @type {Icon}
     * @memberof SaveEntityRequest
     */
    icon?: Icon | null;
}

/**
 * Check if a given object implements the SaveEntityRequest interface.
 */
export function instanceOfSaveEntityRequest(value: object): value is SaveEntityRequest {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function SaveEntityRequestFromJSON(json: any): SaveEntityRequest {
    return SaveEntityRequestFromJSONTyped(json, false);
}

export function SaveEntityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveEntityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'payload': (mapValues(json['payload'], EntityAttributeRequestFromJSON)),
        'icon': json['icon'] == null ? undefined : IconFromJSON(json['icon']),
    };
}

export function SaveEntityRequestToJSON(json: any): SaveEntityRequest {
    return SaveEntityRequestToJSONTyped(json, false);
}

export function SaveEntityRequestToJSONTyped(value?: SaveEntityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'payload': (mapValues(value['payload'], EntityAttributeRequestToJSON)),
        'icon': IconToJSON(value['icon']),
    };
}

