/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LifecycleDomain } from './LifecycleDomain';
import {
    LifecycleDomainFromJSON,
    LifecycleDomainToJSON
} from './LifecycleDomain';
import type { SaveDataConnectorFieldMappingRequest } from './SaveDataConnectorFieldMappingRequest';
import {
    SaveDataConnectorFieldMappingRequestFromJSON,
    SaveDataConnectorFieldMappingRequestToJSON
} from './SaveDataConnectorFieldMappingRequest';
import type { SemanticGroup } from './SemanticGroup';
import {
    SemanticGroupFromJSON,
    SemanticGroupToJSON
} from './SemanticGroup';

/**
 * 
 * @export
 * @interface SaveDataConnectorMappingRequest
 */
export interface SaveDataConnectorMappingRequest {
    /**
     * 
     * @type {LifecycleDomain}
     * @memberof SaveDataConnectorMappingRequest
     */
    lifecycleDomain: LifecycleDomain;
    /**
     * 
     * @type {SemanticGroup}
     * @memberof SaveDataConnectorMappingRequest
     */
    semanticGroup: SemanticGroup;
    /**
     * 
     * @type {Array<SaveDataConnectorFieldMappingRequest>}
     * @memberof SaveDataConnectorMappingRequest
     */
    columns: Array<SaveDataConnectorFieldMappingRequest>;
}



/**
 * Check if a given object implements the SaveDataConnectorMappingRequest interface.
 */
export function instanceOfSaveDataConnectorMappingRequest(value: object): value is SaveDataConnectorMappingRequest {
    if (!('lifecycleDomain' in value) || value['lifecycleDomain'] === undefined) return false;
    if (!('semanticGroup' in value) || value['semanticGroup'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    return true;
}

export function SaveDataConnectorMappingRequestFromJSON(json: any): SaveDataConnectorMappingRequest {
    return SaveDataConnectorMappingRequestFromJSONTyped(json, false);
}

export function SaveDataConnectorMappingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveDataConnectorMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lifecycleDomain': LifecycleDomainFromJSON(json['lifecycleDomain']),
        'semanticGroup': SemanticGroupFromJSON(json['semanticGroup']),
        'columns': ((json['columns'] as Array<any>).map(SaveDataConnectorFieldMappingRequestFromJSON)),
    };
}

export function SaveDataConnectorMappingRequestToJSON(json: any): SaveDataConnectorMappingRequest {
    return SaveDataConnectorMappingRequestToJSONTyped(json, false);
}

export function SaveDataConnectorMappingRequestToJSONTyped(value?: SaveDataConnectorMappingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lifecycleDomain': LifecycleDomainToJSON(value['lifecycleDomain']),
        'semanticGroup': SemanticGroupToJSON(value['semanticGroup']),
        'columns': ((value['columns'] as Array<any>).map(SaveDataConnectorFieldMappingRequestToJSON)),
    };
}

