/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityTypeSemanticMetadata } from './EntityTypeSemanticMetadata';
import {
    EntityTypeSemanticMetadataFromJSON,
    EntityTypeSemanticMetadataToJSON
} from './EntityTypeSemanticMetadata';

/**
 * 
 * @export
 * @interface SemanticMetadataBundle
 */
export interface SemanticMetadataBundle {
    /**
     * 
     * @type {EntityTypeSemanticMetadata}
     * @memberof SemanticMetadataBundle
     */
    entityType?: EntityTypeSemanticMetadata | null;
    /**
     * 
     * @type {{ [key: string]: EntityTypeSemanticMetadata; }}
     * @memberof SemanticMetadataBundle
     */
    attributes: { [key: string]: EntityTypeSemanticMetadata; };
    /**
     * 
     * @type {{ [key: string]: EntityTypeSemanticMetadata; }}
     * @memberof SemanticMetadataBundle
     */
    relationships: { [key: string]: EntityTypeSemanticMetadata; };
}

/**
 * Check if a given object implements the SemanticMetadataBundle interface.
 */
export function instanceOfSemanticMetadataBundle(value: object): value is SemanticMetadataBundle {
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('relationships' in value) || value['relationships'] === undefined) return false;
    return true;
}

export function SemanticMetadataBundleFromJSON(json: any): SemanticMetadataBundle {
    return SemanticMetadataBundleFromJSONTyped(json, false);
}

export function SemanticMetadataBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SemanticMetadataBundle {
    if (json == null) {
        return json;
    }
    return {
        
        'entityType': json['entityType'] == null ? undefined : EntityTypeSemanticMetadataFromJSON(json['entityType']),
        'attributes': (mapValues(json['attributes'], EntityTypeSemanticMetadataFromJSON)),
        'relationships': (mapValues(json['relationships'], EntityTypeSemanticMetadataFromJSON)),
    };
}

export function SemanticMetadataBundleToJSON(json: any): SemanticMetadataBundle {
    return SemanticMetadataBundleToJSONTyped(json, false);
}

export function SemanticMetadataBundleToJSONTyped(value?: SemanticMetadataBundle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entityType': EntityTypeSemanticMetadataToJSON(value['entityType']),
        'attributes': (mapValues(value['attributes'], EntityTypeSemanticMetadataToJSON)),
        'relationships': (mapValues(value['relationships'], EntityTypeSemanticMetadataToJSON)),
    };
}

