/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RelationshipFilter } from './RelationshipFilter';
import {
    RelationshipFilterFromJSONTyped,
    RelationshipFilterToJSONTyped
} from './RelationshipFilter';

/**
 * Entity is related to one of the specified entities.
 * @export
 * @interface TargetEquals
 */
export interface TargetEquals extends RelationshipFilter {
    /**
     * List of entity IDs to match. Supports template expressions.
     * @type {Array<string>}
     * @memberof TargetEquals
     */
    entityIds: Array<string>;
}



/**
 * Check if a given object implements the TargetEquals interface.
 */
export function instanceOfTargetEquals(value: object): value is TargetEquals {
    if (!('entityIds' in value) || value['entityIds'] === undefined) return false;
    return true;
}

export function TargetEqualsFromJSON(json: any): TargetEquals {
    return TargetEqualsFromJSONTyped(json, false);
}

export function TargetEqualsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetEquals {
    if (json == null) {
        return json;
    }
    return {
        ...RelationshipFilterFromJSONTyped(json, true),
        'entityIds': json['entityIds'],
    };
}

export function TargetEqualsToJSON(json: any): TargetEquals {
    return TargetEqualsToJSONTyped(json, false);
}

export function TargetEqualsToJSONTyped(value?: TargetEquals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...RelationshipFilterToJSONTyped(value, true),
        'entityIds': value['entityIds'],
    };
}

