/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { QueryFilter } from './QueryFilter';
import {
    QueryFilterFromJSON,
    QueryFilterToJSON
} from './QueryFilter';
import type { RelationshipFilter } from './RelationshipFilter';
import {
    RelationshipFilterFromJSONTyped,
    RelationshipFilterToJSONTyped
} from './RelationshipFilter';

/**
 * Related entity satisfies nested filter criteria.
 * @export
 * @interface TargetMatches
 */
export interface TargetMatches extends RelationshipFilter {
    /**
     * 
     * @type {QueryFilter}
     * @memberof TargetMatches
     */
    filter: QueryFilter | null;
}



/**
 * Check if a given object implements the TargetMatches interface.
 */
export function instanceOfTargetMatches(value: object): value is TargetMatches {
    if (!('filter' in value) || value['filter'] === undefined) return false;
    return true;
}

export function TargetMatchesFromJSON(json: any): TargetMatches {
    return TargetMatchesFromJSONTyped(json, false);
}

export function TargetMatchesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetMatches {
    if (json == null) {
        return json;
    }
    return {
        ...RelationshipFilterFromJSONTyped(json, true),
        'filter': QueryFilterFromJSON(json['filter']),
    };
}

export function TargetMatchesToJSON(json: any): TargetMatches {
    return TargetMatchesToJSONTyped(json, false);
}

export function TargetMatchesToJSONTyped(value?: TargetMatches | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...RelationshipFilterToJSONTyped(value, true),
        'filter': QueryFilterToJSON(value['filter']),
    };
}

