/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FilterValue } from './FilterValue';
import {
    FilterValueFromJSONTyped,
    FilterValueToJSONTyped
} from './FilterValue';

/**
 * Template expression resolved at execution time.
 * @export
 * @interface Template
 */
export interface Template extends FilterValue {
    /**
     * Template expression using workflow context.
     * @type {string}
     * @memberof Template
     */
    expression: string;
}

/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): value is Template {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    return true;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if (json == null) {
        return json;
    }
    return {
        ...FilterValueFromJSONTyped(json, true),
        'expression': json['expression'],
    };
}

export function TemplateToJSON(json: any): Template {
    return TemplateToJSONTyped(json, false);
}

export function TemplateToJSONTyped(value?: Template | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...FilterValueToJSONTyped(value, true),
        'expression': value['expression'],
    };
}

