/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowNodeConfig } from './WorkflowNodeConfig';
import {
    WorkflowNodeConfigFromJSONTyped,
    WorkflowNodeConfigToJSONTyped
} from './WorkflowNodeConfig';
import type { WorkflowUtilityActionType } from './WorkflowUtilityActionType';
import {
    WorkflowUtilityActionTypeFromJSON,
    WorkflowUtilityActionTypeToJSON
} from './WorkflowUtilityActionType';

/**
 * 
 * @export
 * @interface WorkflowUtilityConfig
 */
export interface WorkflowUtilityConfig extends WorkflowNodeConfig {
    /**
     * 
     * @type {WorkflowUtilityActionType}
     * @memberof WorkflowUtilityConfig
     */
    subType: WorkflowUtilityActionType;
}



/**
 * Check if a given object implements the WorkflowUtilityConfig interface.
 */
export function instanceOfWorkflowUtilityConfig(value: object): value is WorkflowUtilityConfig {
    if (!('subType' in value) || value['subType'] === undefined) return false;
    return true;
}

export function WorkflowUtilityConfigFromJSON(json: any): WorkflowUtilityConfig {
    return WorkflowUtilityConfigFromJSONTyped(json, false);
}

export function WorkflowUtilityConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowUtilityConfig {
    if (json == null) {
        return json;
    }
    return {
        ...WorkflowNodeConfigFromJSONTyped(json, true),
        'subType': WorkflowUtilityActionTypeFromJSON(json['subType']),
    };
}

export function WorkflowUtilityConfigToJSON(json: any): WorkflowUtilityConfig {
    return WorkflowUtilityConfigToJSONTyped(json, false);
}

export function WorkflowUtilityConfigToJSONTyped(value?: WorkflowUtilityConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...WorkflowNodeConfigToJSONTyped(value, true),
        'subType': WorkflowUtilityActionTypeToJSON(value['subType']),
    };
}

