/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowNodeConfig } from './WorkflowNodeConfig';
import {
    WorkflowNodeConfigFromJSONTyped,
    WorkflowNodeConfigToJSONTyped
} from './WorkflowNodeConfig';
import type { WorkflowTriggerType } from './WorkflowTriggerType';
import {
    WorkflowTriggerTypeFromJSON,
    WorkflowTriggerTypeToJSON
} from './WorkflowTriggerType';

/**
 * 
 * @export
 * @interface WorkflowTriggerConfig
 */
export interface WorkflowTriggerConfig extends WorkflowNodeConfig {
    /**
     * 
     * @type {WorkflowTriggerType}
     * @memberof WorkflowTriggerConfig
     */
    subType: WorkflowTriggerType;
}



/**
 * Check if a given object implements the WorkflowTriggerConfig interface.
 */
export function instanceOfWorkflowTriggerConfig(value: object): value is WorkflowTriggerConfig {
    if (!('subType' in value) || value['subType'] === undefined) return false;
    return true;
}

export function WorkflowTriggerConfigFromJSON(json: any): WorkflowTriggerConfig {
    return WorkflowTriggerConfigFromJSONTyped(json, false);
}

export function WorkflowTriggerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTriggerConfig {
    if (json == null) {
        return json;
    }
    return {
        ...WorkflowNodeConfigFromJSONTyped(json, true),
        'subType': WorkflowTriggerTypeFromJSON(json['subType']),
    };
}

export function WorkflowTriggerConfigToJSON(json: any): WorkflowTriggerConfig {
    return WorkflowTriggerConfigToJSONTyped(json, false);
}

export function WorkflowTriggerConfigToJSONTyped(value?: WorkflowTriggerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...WorkflowNodeConfigToJSONTyped(value, true),
        'subType': WorkflowTriggerTypeToJSON(value['subType']),
    };
}

