/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowNodeConfig } from './WorkflowNodeConfig';

/**
 * 
 * @export
 * @interface WorkflowParseConfig
 */
export interface WorkflowParseConfig extends WorkflowNodeConfig {
}



/**
 * Check if a given object implements the WorkflowParseConfig interface.
 */
export function instanceOfWorkflowParseConfig(value: object): value is WorkflowParseConfig {
    return true;
}

export function WorkflowParseConfigFromJSON(json: any): WorkflowParseConfig {
    return WorkflowParseConfigFromJSONTyped(json, false);
}

export function WorkflowParseConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowParseConfig {
    return json;
}

export function WorkflowParseConfigToJSON(json: any): WorkflowParseConfig {
    return WorkflowParseConfigToJSONTyped(json, false);
}

export function WorkflowParseConfigToJSONTyped(value?: WorkflowParseConfig | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

