/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowControlType } from './WorkflowControlType';
import {
    WorkflowControlTypeFromJSON,
    WorkflowControlTypeToJSON
} from './WorkflowControlType';
import type { WorkflowNodeConfig } from './WorkflowNodeConfig';
import {
    WorkflowNodeConfigFromJSONTyped,
    WorkflowNodeConfigToJSONTyped
} from './WorkflowNodeConfig';

/**
 * 
 * @export
 * @interface WorkflowControlConfig
 */
export interface WorkflowControlConfig extends WorkflowNodeConfig {
    /**
     * 
     * @type {WorkflowControlType}
     * @memberof WorkflowControlConfig
     */
    subType: WorkflowControlType;
}



/**
 * Check if a given object implements the WorkflowControlConfig interface.
 */
export function instanceOfWorkflowControlConfig(value: object): value is WorkflowControlConfig {
    if (!('subType' in value) || value['subType'] === undefined) return false;
    return true;
}

export function WorkflowControlConfigFromJSON(json: any): WorkflowControlConfig {
    return WorkflowControlConfigFromJSONTyped(json, false);
}

export function WorkflowControlConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowControlConfig {
    if (json == null) {
        return json;
    }
    return {
        ...WorkflowNodeConfigFromJSONTyped(json, true),
        'subType': WorkflowControlTypeFromJSON(json['subType']),
    };
}

export function WorkflowControlConfigToJSON(json: any): WorkflowControlConfig {
    return WorkflowControlConfigToJSONTyped(json, false);
}

export function WorkflowControlConfigToJSONTyped(value?: WorkflowControlConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...WorkflowNodeConfigToJSONTyped(value, true),
        'subType': WorkflowControlTypeToJSON(value['subType']),
    };
}

