/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldToJSON
} from './WorkflowNodeConfigField';
import type { WorkflowNodeOutputMetadata } from './WorkflowNodeOutputMetadata';
import {
    WorkflowNodeOutputMetadataFromJSON,
    WorkflowNodeOutputMetadataToJSON
} from './WorkflowNodeOutputMetadata';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeToJSON
} from './WorkflowNodeType';
import type { WorkflowNodeTypeMetadata } from './WorkflowNodeTypeMetadata';
import {
    WorkflowNodeTypeMetadataFromJSON,
    WorkflowNodeTypeMetadataToJSON
} from './WorkflowNodeTypeMetadata';

/**
 * 
 * @export
 * @interface WorkflowNodeMetadata
 */
export interface WorkflowNodeMetadata {
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowNodeMetadata
     */
    type: WorkflowNodeType;
    /**
     * 
     * @type {string}
     * @memberof WorkflowNodeMetadata
     */
    subType: string;
    /**
     * 
     * @type {WorkflowNodeTypeMetadata}
     * @memberof WorkflowNodeMetadata
     */
    metadata: WorkflowNodeTypeMetadata;
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowNodeMetadata
     */
    schema: Array<WorkflowNodeConfigField>;
    /**
     * 
     * @type {WorkflowNodeOutputMetadata}
     * @memberof WorkflowNodeMetadata
     */
    outputMetadata?: WorkflowNodeOutputMetadata | null;
}



/**
 * Check if a given object implements the WorkflowNodeMetadata interface.
 */
export function instanceOfWorkflowNodeMetadata(value: object): value is WorkflowNodeMetadata {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('subType' in value) || value['subType'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    return true;
}

export function WorkflowNodeMetadataFromJSON(json: any): WorkflowNodeMetadata {
    return WorkflowNodeMetadataFromJSONTyped(json, false);
}

export function WorkflowNodeMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowNodeMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'type': WorkflowNodeTypeFromJSON(json['type']),
        'subType': json['subType'],
        'metadata': WorkflowNodeTypeMetadataFromJSON(json['metadata']),
        'schema': ((json['schema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
        'outputMetadata': json['outputMetadata'] == null ? undefined : WorkflowNodeOutputMetadataFromJSON(json['outputMetadata']),
    };
}

export function WorkflowNodeMetadataToJSON(json: any): WorkflowNodeMetadata {
    return WorkflowNodeMetadataToJSONTyped(json, false);
}

export function WorkflowNodeMetadataToJSONTyped(value?: WorkflowNodeMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': WorkflowNodeTypeToJSON(value['type']),
        'subType': value['subType'],
        'metadata': WorkflowNodeTypeMetadataToJSON(value['metadata']),
        'schema': ((value['schema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
        'outputMetadata': WorkflowNodeOutputMetadataToJSON(value['outputMetadata']),
    };
}

