/* tslint:disable */
/* eslint-disable */
/**
 * Cranium Core API
 * API documentation for Cranium Core services.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthenticationType } from './AuthenticationType';
import {
    AuthenticationTypeFromJSON,
    AuthenticationTypeToJSON
} from './AuthenticationType';
import type { RequestMethodType } from './RequestMethodType';
import {
    RequestMethodTypeFromJSON,
    RequestMethodTypeToJSON
} from './RequestMethodType';
import type { SchemaString } from './SchemaString';
import {
    SchemaStringFromJSON,
    SchemaStringToJSON
} from './SchemaString';
import type { Signature } from './Signature';
import {
    SignatureFromJSON,
    SignatureToJSON
} from './Signature';
import type { WorkflowNodeConfigField } from './WorkflowNodeConfigField';
import {
    WorkflowNodeConfigFieldFromJSON,
    WorkflowNodeConfigFieldToJSON
} from './WorkflowNodeConfigField';
import type { WorkflowNodeType } from './WorkflowNodeType';
import {
    WorkflowNodeTypeFromJSON,
    WorkflowNodeTypeToJSON
} from './WorkflowNodeType';
import type { WorkflowTriggerType } from './WorkflowTriggerType';
import {
    WorkflowTriggerTypeFromJSON,
    WorkflowTriggerTypeToJSON
} from './WorkflowTriggerType';

/**
 * Configuration for WEBHOOK trigger nodes. Triggers workflow execution when an HTTP webhook is received.
 * @export
 * @interface WorkflowWebhookTriggerConfig
 */
export interface WorkflowWebhookTriggerConfig {
    /**
     * 
     * @type {number}
     * @memberof WorkflowWebhookTriggerConfig
     */
    version: number;
    /**
     * 
     * @type {RequestMethodType}
     * @memberof WorkflowWebhookTriggerConfig
     */
    method: RequestMethodType;
    /**
     * 
     * @type {AuthenticationType}
     * @memberof WorkflowWebhookTriggerConfig
     */
    authentication: AuthenticationType;
    /**
     * 
     * @type {Signature}
     * @memberof WorkflowWebhookTriggerConfig
     */
    signature: Signature;
    /**
     * 
     * @type {SchemaString}
     * @memberof WorkflowWebhookTriggerConfig
     */
    payloadSchema: SchemaString;
    /**
     * 
     * @type {Array<WorkflowNodeConfigField>}
     * @memberof WorkflowWebhookTriggerConfig
     */
    configSchema: Array<WorkflowNodeConfigField>;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof WorkflowWebhookTriggerConfig
     */
    config: { [key: string]: object; };
    /**
     * 
     * @type {WorkflowTriggerType}
     * @memberof WorkflowWebhookTriggerConfig
     */
    subType: WorkflowTriggerType;
    /**
     * 
     * @type {WorkflowNodeType}
     * @memberof WorkflowWebhookTriggerConfig
     */
    type?: WorkflowNodeType;
}



/**
 * Check if a given object implements the WorkflowWebhookTriggerConfig interface.
 */
export function instanceOfWorkflowWebhookTriggerConfig(value: object): value is WorkflowWebhookTriggerConfig {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('authentication' in value) || value['authentication'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('payloadSchema' in value) || value['payloadSchema'] === undefined) return false;
    if (!('configSchema' in value) || value['configSchema'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('subType' in value) || value['subType'] === undefined) return false;
    return true;
}

export function WorkflowWebhookTriggerConfigFromJSON(json: any): WorkflowWebhookTriggerConfig {
    return WorkflowWebhookTriggerConfigFromJSONTyped(json, false);
}

export function WorkflowWebhookTriggerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowWebhookTriggerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'method': RequestMethodTypeFromJSON(json['method']),
        'authentication': AuthenticationTypeFromJSON(json['authentication']),
        'signature': SignatureFromJSON(json['signature']),
        'payloadSchema': SchemaStringFromJSON(json['payloadSchema']),
        'configSchema': ((json['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldFromJSON)),
        'config': json['config'],
        'subType': WorkflowTriggerTypeFromJSON(json['subType']),
        'type': json['type'] == null ? undefined : WorkflowNodeTypeFromJSON(json['type']),
    };
}

export function WorkflowWebhookTriggerConfigToJSON(json: any): WorkflowWebhookTriggerConfig {
    return WorkflowWebhookTriggerConfigToJSONTyped(json, false);
}

export function WorkflowWebhookTriggerConfigToJSONTyped(value?: WorkflowWebhookTriggerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'method': RequestMethodTypeToJSON(value['method']),
        'authentication': AuthenticationTypeToJSON(value['authentication']),
        'signature': SignatureToJSON(value['signature']),
        'payloadSchema': SchemaStringToJSON(value['payloadSchema']),
        'configSchema': ((value['configSchema'] as Array<any>).map(WorkflowNodeConfigFieldToJSON)),
        'config': value['config'],
        'subType': WorkflowTriggerTypeToJSON(value['subType']),
        'type': WorkflowNodeTypeToJSON(value['type']),
    };
}

